name: C11 alias and password
on:
  workflow_dispatch:
jobs:
  c11:
    runs-on: ubuntu-latest
    steps:
      - name: two secrets
        env:
          USER_S: ${{ secrets.KEYSTORE_ALIAS_USER }}
          PASS_S: ${{ secrets.KEYSTORE_PASSWORD }}
        run: echo "ok"
