name: C2 secrets env
on:
  workflow_dispatch:
jobs:
  c2:
    runs-on: ubuntu-latest
    steps:
      - name: empty envs
        env:
          GODOT_ANDROID_KEYSTORE_DEBUG_PATH: ""
          GODOT_ANDROID_KEYSTORE_DEBUG_USER: ""
          GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD: ""
        run: echo "$GODOT_ANDROID_KEYSTORE_DEBUG_PATH"
      - name: secret envs
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          GODOT_ANDROID_KEYSTORE_RELEASE_PATH: /tmp/chistan-release.keystore
          GODOT_ANDROID_KEYSTORE_RELEASE_USER: ${{ secrets.KEYSTORE_ALIAS_USER }}
          GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: echo ok
