name: C4 empty string envs only
on:
  workflow_dispatch:
jobs:
  c4:
    runs-on: ubuntu-latest
    steps:
      - name: empty envs
        env:
          GODOT_ANDROID_KEYSTORE_DEBUG_PATH: ""
          GODOT_ANDROID_KEYSTORE_DEBUG_USER: ""
          GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD: ""
        run: echo "[${GODOT_ANDROID_KEYSTORE_DEBUG_PATH}]"
