name: C6 non-secret expression
on:
  workflow_dispatch:
jobs:
  c6:
    runs-on: ubuntu-latest
    steps:
      - name: gh expr
        env:
          REPO_NAME: ${{ github.repository }}
        run: echo "$REPO_NAME"
