name: C8 github token
on:
  workflow_dispatch:
jobs:
  c8:
    runs-on: ubuntu-latest
    steps:
      - name: built-in token
        env:
          TOK: ${{ secrets.GITHUB_TOKEN }}
        run: echo "tok=${#TOK}"
